using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Logic.Domain.PandoraManagement.Generation;

[Generator]
public sealed class ScriptInstructionFactoryGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Logic.Domain.PandoraManagement.Script.Instructions.ScriptInstructionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var attributes = context.SyntaxProvider.ForAttributeWithMetadataName(AttributeName, (_, _) => true, (attrCtx, _) => attrCtx.Attributes).SelectMany((a, _) => a);

        var allAttributes = attributes.Collect();
        context.RegisterSourceOutput(allAttributes, GenerateFactories);
    }

    private void GenerateFactories(SourceProductionContext productionContext, ImmutableArray<AttributeData> attributes)
    {
        GenerateReaderFactory(productionContext, attributes);
        GenerateComposerFactory(productionContext, attributes);
        GenerateCalculatorFactory(productionContext, attributes);
    }

    private static void GenerateReaderFactory(SourceProductionContext productionContext, ImmutableArray<AttributeData> attributes)
    {
        var sb = new StringBuilder();
        foreach (AttributeData attribute in attributes)
            ProcessReaderAttribute(sb, attribute);

        productionContext.AddSource("ScriptInstructionReaderFactory.g.cs",
            $$"""
              // <auto-generated />
              using Logic.Domain.PandoraManagement.InternalContract.Script.Instructions;
              
              namespace Logic.Domain.PandoraManagement.Script.Instructions;

              internal class ScriptInstructionReaderFactory
              {
                  private static readonly Lazy<ScriptInstructionReaderFactory> Lazy = new(() => new ScriptInstructionReaderFactory());

                  public static ScriptInstructionReaderFactory Instance => Lazy.Value;

                  public IScriptInstructionReader? Get(int instruction)
                  {
                      return instruction switch
                      {
              {{sb}}            _ => null
                      };
                  }
              }
              """);
    }

    private static void GenerateComposerFactory(SourceProductionContext productionContext, ImmutableArray<AttributeData> attributes)
    {
        var sb = new StringBuilder();
        foreach (AttributeData attribute in attributes)
            ProcessComposerAttribute(sb, attribute);

        productionContext.AddSource("ScriptInstructionComposerFactory.g.cs",
            $$"""
              // <auto-generated />
              using Logic.Domain.PandoraManagement.InternalContract.Script.Instructions;
              
              namespace Logic.Domain.PandoraManagement.Script.Instructions;

              internal class ScriptInstructionComposerFactory
              {
                  private static readonly Lazy<ScriptInstructionComposerFactory> Lazy = new(() => new ScriptInstructionComposerFactory());

                  public static ScriptInstructionComposerFactory Instance => Lazy.Value;

                  public IScriptInstructionComposer? Get(int instruction)
                  {
                      return instruction switch
                      {
              {{sb}}            _ => null
                      };
                  }
              }
              """);
    }

    private static void GenerateCalculatorFactory(SourceProductionContext productionContext, ImmutableArray<AttributeData> attributes)
    {
        var sb = new StringBuilder();
        foreach (AttributeData attribute in attributes)
            ProcessCalculatorAttribute(sb, attribute);

        productionContext.AddSource("ScriptInstructionCalculatorFactory.g.cs",
            $$"""
              // <auto-generated />
              using Logic.Domain.PandoraManagement.InternalContract.Script.Instructions;

              namespace Logic.Domain.PandoraManagement.Script.Instructions;

              internal class ScriptInstructionCalculatorFactory
              {
                  private static readonly Lazy<ScriptInstructionCalculatorFactory> Lazy = new(() => new ScriptInstructionCalculatorFactory());

                  public static ScriptInstructionCalculatorFactory Instance => Lazy.Value;

                  public IScriptInstructionCalculator? Get(int instruction)
                  {
                      return instruction switch
                      {
              {{sb}}            _ => null
                      };
                  }
              }
              """);
    }

    private static void ProcessReaderAttribute(StringBuilder sb, AttributeData attribute)
    {
        var instruction = (int)attribute.ConstructorArguments[0].Value!;
        sb.AppendLine($"{new string(' ', 12)}{instruction} => Instruction{instruction}Reader.Instance,");
    }

    private static void ProcessComposerAttribute(StringBuilder sb, AttributeData attribute)
    {
        var instruction = (int)attribute.ConstructorArguments[0].Value!;
        sb.AppendLine($"{new string(' ', 12)}{instruction} => Instruction{instruction}Composer.Instance,");
    }

    private static void ProcessCalculatorAttribute(StringBuilder sb, AttributeData attribute)
    {
        var instruction = (int)attribute.ConstructorArguments[0].Value!;
        sb.AppendLine($"{new string(' ', 12)}{instruction} => Instruction{instruction}Calculator.Instance,");
    }
}